name: build

on:
  push:
    branches: [ master, develop ]

jobs:
  build-develop:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    name: build-develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%SZ')"
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/binklink:staging-${{ steps.date.outputs.date }}
            binkcore.azurecr.io/binklink:staging
  build-master:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build-master
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%SZ')"
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/binklink:prod-${{ steps.date.outputs.date }}
            binkcore.azurecr.io/binklink:prod
            binkcore.azurecr.io/binklink:latest
